### ISSUE TITLE
AttributeError: 'method' object has no attribute '__signature__' in fastapi-cache2==0.2.0

### ISSUE THREAD

**Issue by den4uk** [long2ice/fastapi-cache#115]
The latest change in 0.2.0 has broken an implementation where a function is not decorated using `@cache` syntax.

In Python, a decorator like this:

```python
@cache(ttl=60)
def my_func():
    pass
```

is equivalent to:

```python
def my_func():
    pass

my_func = cache(ttl=60)(my_func)
```

However, when the second approach is used with `fastapi-cache2==0.2.0`, this results in an error:

```
.../lib/python3.10/site-packages/fastapi_cache/decorator.py:68: in wrapper
    func.__signature__ = signature
E   AttributeError: 'method' object has no attribute '__signature__'
```

The reason why this decorating approach is used, is to set the `ttl` value dynamically from settings, which are dynamically injected. I don't see the reason for only supporting the decorated approach, but also have an ability to wrap functions with decorators.

The approach still works fine with `0.1.9`. Looking at the changed files, this is most definitely to do with the latest release.

**Comment by mkdir700** [comment]
I guess you decorated the method with `cache`. When I use `cache` to decorate a function, the exception you mentioned does not occur.

But I think method decoration should be supported, because both methods and functions were allowed before this.

**Comment by mjpieters** [comment]
Why is the `__signature__` attribute placed on the *wrapped* function. Wouldn't it suffice to set this on the `inner` function instead, the replacement function that the decorator returns?
