### PR TITLE
Attach updated endpoint signature to inner

### LINKED ISSUE #115: AttributeError: 'method' object has no attribute '__signature__' in fastapi-cache2==0.2.0
The latest change in 0.2.0 has broken an implementation where a function is not decorated using `@cache` syntax.

In Python, a decorator like this:

```python
@cache(ttl=60)
def my_func():
    pass
```

is equivalent to:

```python
def my_func():
    pass

my_func = cache(ttl=60)(my_func)
```

However, when the second approach is used with `fastapi-cache2==0.2.0`, this results in an error:

```
.../lib/python3.10/site-packages/fastapi_cache/decorator.py:68: in wrapper
    func.__signature__ = signature
E   AttributeError: 'method' object has no attribute '__signature__'
```

The reason why this decorating approach is used, is to set the `ttl` value dynamically from settings, which are dynamically injected. I don't see the reason for only supporting the decorated approach, but also have an ability to wrap functions with decorators.

The approach still works fine with `0.1.9`. Looking at the changed files, this is most definitely to do with the latest release.

### PR DESCRIPTION
**Pull request by mjpieters**
Not all endpoints accept a `__signature__` attribute, nor should the cache decorator modify the decorated endpoint. Attach the signature to the returned inner function instead.

While here, refactor the signature updating code, and extract it to a separate function.

Fixes #115

### CODE REVIEW

**Comment by mjpieters** [comment]
Note: there is one edge-case the decorator isn't handling at the moment: if the decorated endpoint uses the _names_ `request` or `response` but expects these to be a different type:

```
def foo(request: int, response: str, req: Request, resp: Response) -> None:
    pass
```

This is perfectly valid, but the cache decorator will then fail with a `ValueError: duplicate parameter name: 'request'` or `ValueError: duplicate parameter name: 'response'` exception.

To make that work, you'd have to generate unique names for the request and response parameters. That's well outside the scope of this PR however.

**Comment by mjpieters** [comment]
Another issue is that the decorator assumes the request and response parameters always are named 'request' and 'response' when popping these from the `copy_kwargs` dict.
